package com.test.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "Stocks")
public class Stock {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String stockId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userId-index")
    private String userId;

 // "BUY" or "SELL"
    @DynamoDBAttribute private String type;
    @DynamoDBAttribute private String symbol;
    @DynamoDBAttribute private int quantity;

 // For BUY: This is the Cost. 
    // For SELL: This is the Selling Price.
    @DynamoDBAttribute private double purchasePrice;
    @DynamoDBAttribute private double currentPrice;
    @DynamoDBAttribute private double gainLoss;

    @DynamoDBAttribute private Long timestamp;

    // ---- Store date as plain string for DynamoDB ----
    @DynamoDBAttribute(attributeName = "tradeDate")
    private String tradeDate; // <-- final field name (remove LocalDate methods)

}
